# Generated by Django 4.1.4 on 2023-01-08 23:35
import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
import jsonfield.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('symbol_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=15)),
                ('initial_capital', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('heartbeat', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('data_handler', models.CharField(max_length=200)),
                ('execution_handler', models.CharField(max_length=200)),
                ('portfolio', models.CharField(max_length=200)),
                ('strategy', models.CharField(max_length=200)),
                ('strategy_parameters', jsonfield.fields.JSONField(default={})),
                ('data_start_date', models.DateTimeField(verbose_name='data start date')),
                ('data_end_date', models.DateTimeField(verbose_name='data end date')),
                ('portfolio_start_date', models.DateTimeField(verbose_name='portfolio start date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
            ],
        ),
        migrations.CreateModel(
            name='BacktestResults',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', jsonfield.fields.JSONField(default={})),
                ('run_date', models.DateTimeField(auto_now_add=True, verbose_name='updated date')),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.backtest')),
            ],
        ),
    ]
