# Generated by Django 4.1.4 on 2023-01-20 20:15
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('securities_master', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='backtest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.backtest'),
        ),
        migrations.AddField(
            model_name='backtest',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backtest',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.strategy'),
        ),
        migrations.AddField(
            model_name='backtest',
            name='symbol_list',
            field=models.ManyToManyField(blank=True, related_name='symbol_list', to='securities_master.symbol'),
        ),
    ]
